name: yaroorm
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  collection: ^1.18.0
  sqflite_common_ffi: ^2.3.1
  reflectable: ^4.0.5
  analyzer:

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
