name: yaroorm
description: A starting point for Dart libraries or applications.
version: 1.0.0

publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  collection: ^1.18.0
  sqflite_common_ffi: ^2.3.1
  postgres: ^3.0.4
  reflectable:
    git:
      url: https://github.com/codekeyz/reflectable.dart.git
      path: reflectable
  mysql_client: ^0.0.27
  recase: ^4.1.0
  meta: ^1.11.0
  json_annotation: ^4.8.1

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  path:
